# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serviceConn.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11serviceConn.proto\x12\x05proto\"5\n\x10HandshakeRequest\x12!\n\x08peerInfo\x18\x01 \x01(\x0b\x32\x0f.proto.PeerInfo\"5\n\x11HandshakeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x08PeerInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"3\n\x10PeerStatusUpdate\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\"E\n\x12PeerUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"*\n\x08PeerList\x12\x1e\n\x05peers\x18\x01 \x03(\x0b\x32\x0f.proto.PeerInfo\"\x07\n\x05\x45mpty2\xcf\x01\n\x14P2PServiceConnection\x12@\n\tHandshake\x12\x17.proto.HandshakeRequest\x1a\x18.proto.HandshakeResponse\"\x00\x12H\n\x0cMonitorPeers\x12\x17.proto.PeerStatusUpdate\x1a\x19.proto.PeerUpdateResponse\"\x00(\x01\x30\x01\x12+\n\x08GetPeers\x12\x0c.proto.Empty\x1a\x0f.proto.PeerList\"\x00\x42\x43ZAgithub/sgalle16/sgalle16-st0263/P2PFileSharingSystem/client/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serviceConn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub/sgalle16/sgalle16-st0263/P2PFileSharingSystem/client/proto'
  _globals['_HANDSHAKEREQUEST']._serialized_start=28
  _globals['_HANDSHAKEREQUEST']._serialized_end=81
  _globals['_HANDSHAKERESPONSE']._serialized_start=83
  _globals['_HANDSHAKERESPONSE']._serialized_end=136
  _globals['_PEERINFO']._serialized_start=138
  _globals['_PEERINFO']._serialized_end=191
  _globals['_PEERSTATUSUPDATE']._serialized_start=193
  _globals['_PEERSTATUSUPDATE']._serialized_end=244
  _globals['_PEERUPDATERESPONSE']._serialized_start=246
  _globals['_PEERUPDATERESPONSE']._serialized_end=315
  _globals['_PEERLIST']._serialized_start=317
  _globals['_PEERLIST']._serialized_end=359
  _globals['_EMPTY']._serialized_start=361
  _globals['_EMPTY']._serialized_end=368
  _globals['_P2PSERVICECONNECTION']._serialized_start=371
  _globals['_P2PSERVICECONNECTION']._serialized_end=578
# @@protoc_insertion_point(module_scope)
